// <auto-generated />
namespace PYP.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class IntitailCreate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IntitailCreate));
        
        string IMigrationMetadata.Id
        {
            get { return "201608082239554_IntitailCreate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
